// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    'FluentEmoji:1stPlaceMedal': typeof import('~icons/fluent-emoji/1st-place-medal')['default']
    FluentEmoji1stPlaceMedal: typeof import('~icons/fluent/emoji1st-place-medal')['default']
    IcBaselineWarning: typeof import('~icons/ic/baseline-warning')['default']
    IcRoundEmojiTransportation: typeof import('~icons/ic/round-emoji-transportation')['default']
    'Mdi:wifiLockOpen': typeof import('~icons/mdi/wifi-lock-open')['default']
    MdiBaselineWarning: typeof import('~icons/mdi/baseline-warning')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
