// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseDialog: typeof import('./components/dialog/BaseDialog.vue')['default']
    'Bx:errorCircle': typeof import('~icons/bx/error-circle')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogDescription: typeof import('@headlessui/vue')['DialogDescription']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    'Ep:close': typeof import('~icons/ep/close')['default']
    'MaterialSymbols:commentBankRounded': typeof import('~icons/material-symbols/comment-bank-rounded')['default']
    'Mdi:commentBankRounded': typeof import('~icons/mdi/comment-bank-rounded')['default']
    Notifications: typeof import('./components/notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleTable: typeof import('./components/table/SimpleTable.vue')['default']
    TextArea: typeof import('./components/form/TextArea.vue')['default']
    TextField: typeof import('./components/form/TextField.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    Verse: typeof import('./components/bible/Verse.vue')['default']
  }
}
