// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'AntDesign:checkCircleOutlined': typeof import('~icons/ant-design/check-circle-outlined')['default']
    Base: typeof import('./components/dialog/base.vue')['default']
    BaseDialog: typeof import('./components/dialog/BaseDialog.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    'Bx:errorCircle': typeof import('~icons/bx/error-circle')['default']
    'Clarity:windowCloseLine': typeof import('~icons/clarity/window-close-line')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogDescription: typeof import('@headlessui/vue')['DialogDescription']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    'Ep:circleClose': typeof import('~icons/ep/circle-close')['default']
    'Ep:close': typeof import('~icons/ep/close')['default']
    MdiCheck: typeof import('~icons/mdi/check')['default']
    MdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    MdiCheckCircleOutine: typeof import('~icons/mdi/check-circle-outine')['default']
    MdiCheckCircleOutline: typeof import('~icons/mdi/check-circle-outline')['default']
    MdiCircleCheck: typeof import('~icons/mdi/circle-check')['default']
    Noti: typeof import('./components/noti.vue')['default']
    Notifications: typeof import('./components/notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snacks: typeof import('./components/snacks.vue')['default']
    TextField: typeof import('./components/form/TextField.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
